### ISSUE TITLE
请教下，CFG lock VT-d SGX CSM RTC Lock 这些偏移量用什么工具查出来的，特征值是什么呢

### ISSUE THREAD

**Issue by liubo20190515** [zmlu/Hackintosh-OC-Colorful-C.B150M-i5-6500-Skylake-HD530#1]
请教下，CFG lock VT-d SGX CSM RTC Lock 这些偏移量用什么工具查出来的，特征值是什么呢

**Comment by zmlu** [comment]
请参考这个链接 [https://www.bilibili.com/read/cv4646116](https://www.bilibili.com/read/cv4646116)
