### ISSUE TITLE
Sierra Possibility...

### ISSUE THREAD

**Issue by aiSanaul** [zmlu/Hackintosh-OC-Colorful-C.B150M-i5-6500-Skylake-HD530#11]
Is there a way to install Sierra or High Sierra on Skylake?
I have a DELL OptiPlex 3050, while installing Sierra/High Sierra on my PC booting ends with these lines:

39:618 00:041 OC: Prelinked status - Success
39:933 00:314 OCSMC: SmcReadValue Key 4D535463 Size 1
39:959 00:026 OCSMC: SmcReadValue Key 4D534163 Size 2

Wondering If you can help me on this, will really appreciate the help.

**Comment by zmlu** [comment]
Maybe you could check this repo https://github.com/carlclone/Optiplex-3050-OSX86

**Comment by aiSanaul** [comment]
Thank you very much. Really helpful, will give it a try ASAP.
