### ISSUE TITLE
【求教】用不了

### ISSUE THREAD

**Issue by yijiepifu** [zmlu/Hackintosh-OC-Colorful-C.B150M-i5-6500-Skylake-HD530#2]
进不了安装界面
![硬件参数](https://user-images.githubusercontent.com/8278902/155182883-fba24288-2be2-4f2b-abab-1651ed262e7c.png)

**Comment by zmlu** [comment]
参考说明文档中“主板配置”，开启和关闭对应的功能，你的主板跟我的不一样，不要参考我给的类似0x开头的位置
