### ISSUE TITLE
youtube not working 

### ISSUE THREAD

**Issue by ygorluiz** [zmlu/Hackintosh-OC-Colorful-C.B150M-i5-6500-Skylake-HD530#5]
do you know what it could be?

**Comment by zmlu** [comment]
Maybe cause of DRM problem. Normal, DRM is broken on iGPUs.

Reference: [https://dortania.github.io/OpenCore-Post-Install/universal/drm.html](https://dortania.github.io/OpenCore-Post-Install/universal/drm.html)

**Comment by zmlu** [comment]
Try use Mozilla Firefox or Chromium-based browsers like Google Chrome and Microsoft Edge

**Comment by ygorluiz** [comment]
@zmlu thx for ur reply, but i fixed removing -igfxsklaskbl and updating weg to development in this latest version you don't need this flag
