### ISSUE TITLE
Youtube not working

### ISSUE THREAD

**Issue by su-jang** [zmlu/Hackintosh-OC-Colorful-C.B150M-i5-6500-Skylake-HD530#6]
Thank you for your contribution.
I can not play youtube at all. 
I've read a related issue closed recently, but I am still struggling to overcome this issue.
As someone said I tried to remove --igfxsklaskbl argument but it did not work. And I can not find WEG Developer build.
It would be very appreciated if you would give me some tips.
Regards

**Comment by zmlu** [comment]
You can find WEG Dev build via [https://dortania.github.io/builds/?product=WhateverGreen&viewall=true](https://dortania.github.io/builds/?product=WhateverGreen&viewall=true).

And try Chrome or Edge Browsers.

Good luck.

**Comment by su-jang** [comment]
Thank you for your reply. I think I need some more research.
