### ISSUE TITLE
U盘镜像启动时卡在busy timeout

### ISSUE THREAD

**Issue by xiyuxy** [zmlu/Hackintosh-OC-Colorful-C.B150M-i5-6500-Skylake-HD530#9]
![image](https://user-images.githubusercontent.com/55520317/225169854-1de25bff-2c78-4ae4-bd13-5f5f0db9b34e.jpeg)

busy timeout appleacpicpu

**Comment by zmlu** [comment]
是否对配置做过修改？

**Comment by xiyuxy** [comment]
> 是否对配置做过修改？

完全没有修改

**Comment by zmlu** [comment]
换一个USB插孔安装试试

**Comment by xiyuxy** [comment]
> 换一个USB插孔安装试试
不行还是一样的问题，可能是显卡的问题，每次都是卡着
failed lookup name=com.apple.logd   …………=displaypolicyd

**Comment by xiyuxy** [comment]
然后才会出现  busy timeout

**Comment by zmlu** [comment]
有独显吗？

**Comment by xiyuxy** [comment]
> 有独显吗？

没有独显

**Comment by xiyuxy** [comment]
> 有独显吗？

我没有另外生成CPUfriend,和这个有关系吗

**Comment by zmlu** [comment]
如果配置完全一样，那只能把CPUFriend的kext禁用掉试试

**Comment by zmlu** [comment]
> 如果配置完全一样，那只能把CPUFriend的kext禁用掉试试

CPUFriendDataProvider.kext也禁掉

**Comment by xiyuxy** [comment]
> > 如果配置完全一样，那只能把CPUFriend的kext禁用掉试试
> 
> 
> 
> CPUFriendDataProvider.kext也禁掉

两个都禁用了，也是一样的问题。你是用虚拟机安装然后用这个efi启动，还是直接就用这个efi安装？
我的主板是华硕b150m-plus，cpu是i5-6500  用同样的配置可以安装和启动macos high sierra完全没有问题，但是安装或者启动ventura就不行

**Comment by zmlu** [comment]
我直接用 /ventura 文件夹下的efi安装的，

ventura取消了6代cpu的核显支持，启动参数没改把？

**Comment by xiyuxy** [comment]
> 我直接用 /ventura 文件夹下的efi安装的，
> 
> 
> 
> ventura取消了6代cpu的核显支持，启动参数没改把？

只是加了 -v别的都没动

**Comment by xiyuxy** [comment]
更新oc到0.9
用dd直接把镜像写入硬盘
然后改显卡为HD620安装成功，启动成功。
然后再把显卡改为HD630也能启动成功。
不知道问题出在哪里？
